### ISSUE TITLE
大佬这个东西怎么用

### ISSUE THREAD

**Issue by xiaoshi1994** [wudision0416/double11#1]
大佬这个东西怎么用？提供一个apk包呗

**Comment by xiaoshi1994** [comment]
可以用了 大佬66666

**Comment by xiaoshi1994** [comment]
大佬 有问题啊？自己点得话能分到2万喵币，但是用你的脚本只能分到200喵币了，而且后面还报null了

**Comment by wudision0416** [comment]
半桶水害死人，sorry，，关于被制裁，我暂时还找不到原因和解决办法，抱歉，
null这个是解决了，

**Comment by wudision0416** [comment]
新版本的淘宝会检测后台，发现脚本工具，需要使用9.0.0的版本，经验证，已解决问题

**Comment by xiaoshi1994** [comment]
好的好的 谢谢，麻烦打一个最新的apk包出来，谢谢
